// constants/subjects.ts
export const MASTER_SUBJECT_LIST = [
  // Home Language options
  'Afrikaans Home Language',
  'English Home Language',
  'isiNdebele Home Language',
  'isiXhosa Home Language',
  'isiZulu Home Language',
  'Sepedi Home Language',
  'Sesotho Home Language',
  'Setswana Home Language',
  'siSwati Home Language',
  'Tshivenda Home Language',
  'Xitsonga Home Language',
  // First Additional Language options
  'Afrikaans First Additional Language',
  'English First Additional Language',
  'isiNdebele First Additional Language',
  'isiXhosa First Additional Language',
  'isiZulu First Additional Language',
  'Sepedi First Additional Language',
  'Sesotho First Additional Language',
  'Setswana First Additional Language',
  'siSwati First Additional Language',
  'Tshivenda First Additional Language',
  'Xitsonga First Additional Language',
  // Maths
  'Mathematics',
  'Mathematical Literacy',
  // Electives
  'Accounting',
  'Agricultural Management Practices',
  'Agricultural Sciences',
  'Agricultural Technology',
  'Business Studies',
  'Civil Technology',
  'Computer Applications Technology',
  'Consumer Studies',
  'Dance Studies',
  'Dramatic Arts',
  'Economics',
  'Electrical Technology',
  'Engineering Graphics and Design',
  'Geography',
  'History',
  'Hospitality Studies',
  'Information Technology',
  'Life Sciences',
  'Mechanical Technology',
  'Music',
  'Physical Sciences',
  'Religion Studies',
  'Tourism',
  'Visual Arts',
];

export const NUM_SUBJECT_SLOTS = 6;
