import * as SQLite from "expo-sqlite";

type CourseSeed = {
  faculty: string;
  qualification: string;
  qualification_type: string;
  duration: string;
  minimum_aps: number | null;
  fps: string | null;
  english_hl: string | null;
  english_fal: string | null;
  mathematics: string | null;
  mathematical_literacy: string | null;
  physical_sciences: string | null;
  life_sciences: string | null;
  nbt: string | null;
  additional_requirements: string;
  apply_url: string;
};

const TALETSO_COURSES: CourseSeed[] = [
  // ======================================================
  // BUSINESS STUDIES
  // ======================================================

  {
    faculty: "Business Studies",
    qualification: "Business Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Financial Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Human Resource Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Management Assistant N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Marketing Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Public Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3.",
    apply_url: "",
  },

  // ======================================================
  // ENGINEERING STUDIES
  // ======================================================

  {
    faculty: "Engineering Studies",
    qualification: "Civil Engineering N1–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics & Physical Sciences or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Electrical Engineering N1–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics & Physical Sciences or relevant N3.",
    apply_url: "",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Mechanical Engineering N1–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics & Physical Sciences or relevant N3.",
    apply_url: "",
  },

  // ======================================================
  // NATIONAL CERTIFICATE (VOCATIONAL) – NC(V)
  // ======================================================

  {
    faculty: "Business Studies",
    qualification: "Management",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Office Administration",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Business Studies",
    qualification: "Finance, Economics & Accounting",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Information Technology",
    qualification: "Information Technology & Computer Science",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Civil Engineering & Building Construction",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Engineering & Related Design",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Electrical Infrastructure Construction",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Hospitality",
    qualification: "Hospitality",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Tourism",
    qualification: "Tourism",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },

  {
    faculty: "Agriculture",
    qualification: "Primary Agriculture",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher.",
    apply_url: "",
  },
];