import * as SQLite from "expo-sqlite";

// ======================================================
// ORBIT TVET COLLEGE
// ======================================================

export const ORBIT_COURSES = [

  // ======================================================
  // BUSINESS STUDIES (NATED)
// ======================================================

  {
    faculty: "Business Studies",
    qualification: "Business Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Financial Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Human Resource Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Management Assistant N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Marketing Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Public Management N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  // ======================================================
  // TOURISM
  // ======================================================

  {
    faculty: "Tourism",
    qualification: "Tourism N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  // ======================================================
  // HOSPITALITY
  // ======================================================

  {
    faculty: "Hospitality",
    qualification: "Hospitality & Catering Services N4–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  // ======================================================
  // ENGINEERING STUDIES (NATED)
  // ======================================================

  {
    faculty: "Engineering Studies",
    qualification: "Electrical Engineering N1–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics and Physical Sciences or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Mechanical Engineering N1–N6",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics and Physical Sciences or relevant N3",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Fitting & Turning N1–N3",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Grade 12 with Mathematics and Physical Sciences",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Boilermaking",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant qualification",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Welding",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant qualification",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Diesel Mechanic",
    qualification_type: "NATED (Report 191)",
    duration: "18 Months",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 12 or relevant qualification",
    apply_url: "https://www.orbitcollege.co.za",
  },

  // ======================================================
  // NATIONAL CERTIFICATE (VOCATIONAL) – NC(V)
  // ======================================================

  {
    faculty: "Engineering Studies",
    qualification: "Civil Engineering & Building Construction",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Engineering & Related Design",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Engineering Studies",
    qualification: "Electrical Infrastructure Construction",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Information Technology",
    qualification: "Information Technology & Computer Science",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Finance, Economics & Accounting",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Management",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Business Studies",
    qualification: "Office Administration",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Hospitality",
    qualification: "Hospitality",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Tourism",
    qualification: "Tourism",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Agriculture",
    qualification: "Primary Agriculture",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Transport & Logistics",
    qualification: "Transport & Logistics",
    qualification_type: "National Certificate (Vocational) [NC(V)]",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Grade 9 or higher",
    apply_url: "https://www.orbitcollege.co.za",
  },

  // ======================================================
  // OCCUPATIONAL PROGRAMMES & SKILLS TRAINING
  // ======================================================

  {
    faculty: "Occupational Programmes",
    qualification: "Automotive Repair & Maintenance",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Diesel Mechanic",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Welding",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Jewellery Design & Manufacture",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Robotics & Artificial Intelligence",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Multimedia",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Hairdressing",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Beauty & Nail Technology",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Apprenticeships",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Learnerships",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Trade Test Preparation",
    qualification_type: "Skills Training",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Artisan Development",
    qualification_type: "Occupational Programme",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },

  {
    faculty: "Occupational Programmes",
    qualification: "Entrepreneurship Programmes",
    qualification_type: "Skills Training",
    duration: "Not Specified",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: null,
    apply_url: "https://www.orbitcollege.co.za",
  },
];

// ======================================================
// SEED ORBIT TVET COLLEGE
// ======================================================

export const seedOrbit = async (db: SQLite.SQLiteDatabase) => {
  const orbit = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["Orbit TVET College"]
  );

  if (!orbit) {
    throw new Error("Orbit TVET College not found.");
  }

  const institutionId = orbit.id;

  for (const course of ORBIT_COURSES) {
    const existing = await db.getFirstAsync<{ id: number }>(
      `SELECT id FROM courses
       WHERE institution_id = ?
       AND qualification = ?`,
      [institutionId, course.qualification]
    );

    if (existing) {
      continue;
    }

    await db.runAsync(
      `INSERT INTO courses (
        institution_id,
        institution_type,
        faculty,
        qualification,
        qualification_type,
        duration,
        province,
        minimum_aps,
        fps,
        english_hl,
        english_fal,
        mathematics,
        mathematical_literacy,
        physical_sciences,
        life_sciences,
        nbt,
        additional_requirements,
        apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        institutionId,
        "tvet",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "North West",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ]
    );
  }

  console.log(
    `Orbit TVET College seeded: ${ORBIT_COURSES.length} courses across faculties.`
  );
};