import { SQLiteDatabase } from "expo-sqlite";

export async function seedUCT(db: SQLiteDatabase) {
  console.log("🌱 Seeding University of Cape Town courses...");

  const courses = [
    // FACULTY OF COMMERCE
    // ==============================

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Computer Science",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Economics",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Economics with Law",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Finance, Investment and Banking",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Finance with Accounting",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Information Systems",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],

    [
      1,
      "university",
      "Commerce",
      "Bachelor of Business Science specialising in Marketing",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      36,
      "50%",
      "60%",
      "70%",
      "No",
      "",
      "",
      "Upper Intermediate (AL & QL)",
      "Mathematical Studies and Maths Main are not accepted.",
    ],
    // FACULTY OF ENGINEERING & THE BUILT ENVIRONMENT
    // ======================================================

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Chemical Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Civil Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Electrical Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Electrical & Computer Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Mechatronics",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Mechanical Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Engineering in Mechanical & Mechatronic Engineering",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "500 FPS (Guaranteed)",
      "50%",
      "60%",
      "80%",
      "No",
      "75%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 420 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Geomatics",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "450 FPS (Guaranteed)",
      "50%",
      "60%",
      "75%",
      "No",
      "70%",
      "",
      "NBT Mathematics, AL & QL",
      "Possible admission from 390 FPS; Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Construction Studies",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "",
      "50%",
      "60%",
      "",
      "No",
      "",
      "",
      "",
      "Mathematical Studies/Mathematical Literacy not accepted."
    ],

    [
      1,
      "university",
      "Engineering & the Built Environment",
      "Bachelor of Science in Property Studies",
      "Bachelor's Degree",
      "4 Years",
      "Western Cape",
      null,
      "",
      "50%",
      "60%",
      "",
      "No",
      "",
      "",
      "",
      "Mathematical Studies/Mathematical Literacy not accepted."
    ],
// FACULTY OF SCIENCE
// ======================================================

  [
    1,
    "university",
    "Science",
    "Bachelor of Science (Applied Biology)",
    "Bachelor's Degree",
    "3 Years",
    "Western Cape",
    null,
    "",
    "50%",
    "60%",
    "70%",
    "No",
    "",
    "",
    "NBT AL & QL",
    "Major: Applied Biology"
  ],

[
1,
"university",
"Science",
"Bachelor of Science (Astronomy)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"70%",
"",
"NBT AL & QL",
"Major: Astronomy"
],

[
1,
"university",
"Science",
"Bachelor of Science (Biochemistry)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"70%",
"No",
"",
"",
"NBT AL & QL",
"Major: Biochemistry"
],

[
1,
"university",
"Science",
"Bachelor of Science (Chemistry)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"70%",
"",
"NBT AL & QL",
"Major: Chemistry"
],

[
1,
"university",
"Science",
"Bachelor of Science (Computer Science)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Computer Science"
],

[
1,
"university",
"Science",
"Bachelor of Science (Computer Games Development)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Computer Games Development"
],

[
1,
"university",
"Science",
"Bachelor of Science (Data Science)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Data Science"
],

[
1,
"university",
"Science",
"Bachelor of Science (Ecology and Evolution)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"70%",
"No",
"",
"",
"NBT AL & QL",
"Major: Ecology and Evolution"
],

[
1,
"university",
"Science",
"Bachelor of Science (Environmental and Geographical Science)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"70%",
"No",
"",
"",
"NBT AL & QL",
"Major: Environmental and Geographical Science"
],

[
1,
"university",
"Science",
"Bachelor of Science (Geology)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"70%",
"No",
"60%",
"",
"NBT AL & QL",
"Major: Geology"
],

[
1,
"university",
"Science",
"Bachelor of Science (Marine Biology)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"70%",
"No",
"",
"",
"NBT AL & QL",
"Major: Marine Biology"
],

[
1,
"university",
"Science",
"Bachelor of Science (Mathematics)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Mathematics"
],

[
1,
"university",
"Science",
"Bachelor of Science (Mathematical Statistics)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Mathematical Statistics"
],

[
1,
"university",
"Science",
"Bachelor of Science (Physics)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"70%",
"",
"NBT AL & QL",
"Major: Physics"
],

[
1,
"university",
"Science",
"Bachelor of Science (Statistics)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"80%",
"No",
"",
"",
"NBT AL & QL",
"Major: Statistics"
],
// ======================================================
// UNIVERSITY OF CAPE TOWN
// FACULTY OF LAW
// ======================================================

[
  1,
  "university",
  "Law",
  "Bachelor of Laws (LLB)",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "",
  "Yes",
  "",
  "",
  "NBT Academic Literacy (AL)",
  "Applicants must meet the Faculty of Law admission requirements. Mathematical Literacy is accepted."
],
// ======================================================
// UNIVERSITY OF CAPE TOWN
// FACULTY OF HEALTH SCIENCES
// ======================================================

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Medicine and Bachelor of Surgery (MBChB)",
  "Bachelor's Degree",
  "6 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "80%",
  "No",
  "80%",
  "",
  "NBT AL, QL & Mathematics",
  "Selection programme. Competitive admission process."
],

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Science in Audiology",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "60%",
  "Yes",
  "",
  "",
  "NBT AL & QL",
  "Faculty admission requirements apply."
],

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Science in Occupational Therapy",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "60%",
  "Yes",
  "",
  "",
  "NBT AL & QL",
  "Faculty admission requirements apply."
],

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Science in Physiotherapy",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "70%",
  "No",
  "70%",
  "",
  "NBT AL & QL",
  "Faculty admission requirements apply."
],

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Science in Speech-Language Pathology",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "60%",
  "Yes",
  "",
  "",
  "NBT AL & QL",
  "Faculty admission requirements apply."
],

[
  1,
  "university",
  "Health Sciences",
  "Bachelor of Nursing",
  "Bachelor's Degree",
  "4 Years",
  "Western Cape",
  null,
  "",
  "60%",
  "60%",
  "Yes",
  "",
  "",
  "NBT AL & QL",
  "Faculty admission requirements apply."
],
// ======================================================
// UNIVERSITY OF CAPE TOWN
// FACULTY OF HUMANITIES
// ======================================================

[
1,
"university",
"Humanities",
"Bachelor of Arts (BA)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"General Humanities degree with majors selected after admission."
],

[
1,
"university",
"Humanities",
"Bachelor of Social Science (BSocSc)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"General Social Science degree with majors selected after admission."
],

[
1,
"university",
"Humanities",
"Bachelor of Social Science in Philosophy, Politics and Economics (BSocSc PPE)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"Structured PPE degree in Philosophy, Politics and Economics."
],

[
1,
"university",
"Humanities",
"Bachelor of Arts in Fine Art (BA FA)",
"Bachelor's Degree",
"4 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"Portfolio submission and supplementary Fine Art application questionnaire required."
],

[
1,
"university",
"Humanities",
"Bachelor of Arts in Theatre & Performance (BA T&P)",
"Bachelor's Degree",
"4 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"Audition required for admission."
],

[
1,
"university",
"Humanities",
"Bachelor of Music (BMus)",
"Bachelor's Degree",
"4 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"Audition required; available in General, Performance, Music Technology and Composition streams."
],

[
1,
"university",
"Humanities",
"Bachelor of Social Work (BSW)",
"Bachelor's Degree",
"4 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"May require an admissions interview; limited annual intake and registration with the South African Council for Social Service Professions pathway."
],

[
1,
"university",
"Humanities",
"Bachelor of Arts specialising in Film and Media Production (BA FMP)",
"Bachelor's Degree",
"3 Years",
"Western Cape",
null,
"",
"50%",
"60%",
"",
"Yes",
"",
"",
"NBT Academic Literacy (AL) and Quantitative Literacy (QL)",
"Students enter through the BA and are selected into the Film and Media Production specialisation during the second year."
  ]
];

  const insertQuery = `
    INSERT INTO courses (
      institution_id,
      institution_type,
      faculty,
      qualification,
      qualification_type,
      duration,
      province,
      minimum_aps,
      english_hl,
      english_fal,
      mathematics,
      mathematical_literacy,
      physical_sciences,
      life_sciences,
      nbt,
      additional_requirements,
      apply_url
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `;

  for (const course of courses) {
    await db.runAsync(insertQuery, course);
  }

  console.log("✅ UCT courses seeded successfully");
}
