//Faculty of AgriSciences
(
  2,
  'University',
  'Faculty of AgriSciences',
  'BSc in Forestry (Forestry & Natural Resources Sciences)',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '60%',
  NULL,
  '50%',
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of AgriSciences',
  'BSc in Forestry (Wood & Wood Products Sciences)',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '70%',
  NULL,
  '50%',
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of AgriSciences',
  'BAgric in Agricultural Production & Management',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific Mathematics and Physical Sciences requirements; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of AgriSciences',
  'BScAgric',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific Mathematics and Physical Sciences requirements; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of AgriSciences',
  'BSc Food Science',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific Mathematics and Physical Sciences requirements; Selection',
  'https://www.sun.ac.za'
),

//Faculty of Arts and Social Sciences
(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'Bachelor of Arts (BA)',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Faculty selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA International Studies',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA Humanities',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA Language and Culture',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA Development and Environment',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA Sport Science',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Arts and Social Sciences',
  'BA in Music',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  '40%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Home Language 50%; First Additional Language 40%; Audition and theory test required',
  'https://www.sun.ac.za'
),

//Faculty of Economic and Management Sciences
(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BCom',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '60%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 65%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BCom Management Sciences',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '60%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 65%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BCom Financial Accounting',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '70%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BCom Investment Management',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '70%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BCom Mathematical Sciences',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '80%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Economic and Management Sciences',
  'BAccounting',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  '70%',
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

//Faculty of Education
(
  2,
  'University',
  'Faculty of Education',
  'BEd Foundation Phase',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific requirements',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Education',
  'BEd Intermediate Phase',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific requirements',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Education',
  'BEd Senior Phase & FET',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%; Programme-specific requirements',
  'https://www.sun.ac.za'
),

//Faculty of Engineering
(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Civil',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Electrical & Electronic',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Industrial',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Mechanical',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Mechatronic',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Engineering',
  'BEng Chemical',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'NSC Aggregate 70%',
  'https://www.sun.ac.za'
),

//Faculty of Law
(
  2,
  'University',
  'Faculty of Law',
  'BA Law',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '60%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Law',
  'BCom Law',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '60%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 65%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Law',
  'LLB',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  '60%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 65%',
  'https://www.sun.ac.za'
),

//Faculty of Medicine and Health Sciences
(
  2,
  'University',
  'Faculty of Medicine and Health Sciences',
  'MBChB',
  'Degree',
  '6 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '70%',
  NULL,
  NULL,
  'Competitive Selection; NSC Aggregate is not a fixed minimum',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Medicine and Health Sciences',
  'Occupational Therapy',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '60%',
  '60%',
  NULL,
  'Competitive Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Medicine and Health Sciences',
  'Physiotherapy',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '60%',
  '60%',
  NULL,
  'Competitive Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Medicine and Health Sciences',
  'Dietetics',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '60%',
  '60%',
  NULL,
  'Competitive Selection',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Medicine and Health Sciences',
  'Speech-Language and Hearing Therapy',
  'Degree',
  '4 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '50%',
  '60%',
  NULL,
  'Competitive Selection',
  'https://www.sun.ac.za'
),

//Faculty of Science
(
  2,
  'University',
  'Faculty of Science',
  'BSc Biological Sciences',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '50%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Physical Sciences',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Computer Science',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Applied Mathematics',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Chemistry',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Physics',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '70%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Earth Sciences',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

(
  2,
  'University',
  'Faculty of Science',
  'BSc Molecular Biology & Biotechnology',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  NULL,
  NULL,
  '60%',
  NULL,
  '60%',
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
),

//Faculty of Theology
(
  2,
  'University',
  'Faculty of Theology',
  'Bachelor of Theology',
  'Degree',
  '3 years',
  'Western Cape',
  NULL,
  '50%',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'NSC Aggregate 60%',
  'https://www.sun.ac.za'
)