import * as SQLite from "expo-sqlite";

type CourseSeed = {
  faculty: string;
  qualification: string;
  qualification_type: string;
  duration: string;
  minimum_aps: number | null;
  fps: string | null;
  english_hl: string | null;
  english_fal: string | null;
  mathematics: string | null;
  mathematical_literacy: string | null;
  physical_sciences: string | null;
  life_sciences: string | null;
  nbt: string | null;
  additional_requirements: string;
  apply_url: string;
};

export const UWC_COURSES: CourseSeed[] = [
  // Faculty of Natural Sciences
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Biotechnology (4 Year) (Code 3007)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Applied Geology (4 Year) (Code 3011)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Biodiversity and Conservation Biology (4 Year) (Code 3015)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences and Physical Sciences recommended",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Chemical Sciences (4 Year) (Code 3019)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Computer Science (4 Year) (Code 3023)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences recommended",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Environmental and Water Science (4 Year) (Code 3027)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Mathematics and Statistical Sciences – Mathematics (4 Year) (Code 3031)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics Level 5 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Mathematics and Statistical Sciences – Statistics (4 Year) (Code 3031)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics Level 5 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Medical Bioscience (4 Year) (Code 3035)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences and Physical Sciences required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Physical Science (4 Year) (Code 3120)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: "Level 5",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 5",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Biotechnology (Code 3211)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Applied Geology (Code 3214)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Biodiversity and Conservation Biology (Code 3217)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences and Physical Sciences recommended",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Chemical Sciences (Code 3220)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Computer Science (Code 3221)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics Level 5 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Mathematics and Statistical Sciences – Mathematics (Code 3227)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics Level 5 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Mathematics and Statistical Sciences – Statistics (Code 3227)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics Level 5 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Medical Bioscience (Code 3230)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences and Physical Sciences required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Physical Science (Code 3233)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: "Level 5",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 5",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "Bachelor of Pharmacy (BPharm) (Code 3305)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "Not Accepted",
  physical_sciences: "Level 5",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 5; selection applies",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Natural Sciences",
  qualification: "BSc Environmental and Water Science (Code 3331)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 4",
  apply_url: "https://www.uwc.ac.za"
},
// Faculty of Law
{
  faculty: "Faculty of Law",
  qualification: "Higher Certificate in Forensic Examination (Code 7115)",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "NSC Higher Certificate admission requirements",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law",
  qualification: "Bachelor of Laws (LLB) – 4 Year (Full-Time) (Code 7161)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another official language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law",
  qualification: "Bachelor of Laws (LLB) – 4 Year (Full-Time) (Code 7162)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another official language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law",
  qualification: "Bachelor of Laws (LLB) – 5 Year (Extended) (Code 7171)",
  qualification_type: "Degree (Extended)",
  duration: "5 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law",
  qualification: "Bachelor of Laws (LLB) – 5 Year (Extended) (Code 7172)",
  qualification_type: "Degree (Extended)",
  duration: "5 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law*",
  qualification: "Bachelor of Commerce in Law (Code 7211)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Admission requirements align with the BCom in Law programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Law*",
  qualification: "Bachelor of Arts in Law (Code 7221)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Admission requirements align with the BA in Law programme",
  apply_url: "https://www.uwc.ac.za"
},
//Faculty of Education
{
  faculty: "Faculty of Education",
  qualification: "BEd (5 Years) Languages and Life Orientation (Code 4091)",
  qualification_type: "Degree (Extended)",
  duration: "5 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd (5 Years) Mathematics and Natural Sciences (Code 4092)",
  qualification_type: "Degree (Extended)",
  duration: "5 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Life Sciences may be required depending on the stream",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Senior Phase & FET – Accounting (FET), EMS & Mathematics (SP) (Code 4401)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Accounting, Business Studies or Economics may be required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Senior Phase & FET – Languages (SP & FET) & Life Orientation (SP) (Code 4402)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Appropriate language subjects required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Senior Phase & FET – Languages (SP & FET) & Mathematics (SP) (Code 4403)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Senior Phase & FET – Languages (SP & FET) & Social Sciences (SP) (Code 4404)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Geography and/or History recommended",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Senior Phase – Mathematics (SP), Mathematical Literacy (FET) & Natural Sciences (SP) (Code 4405)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics and Natural Sciences subject requirements apply",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Languages and Social Sciences (Code 4512)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Appropriate language subjects required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Languages and Life Orientation (Code 4513)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Appropriate language subjects required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd EMS and Social Sciences (Code 4514)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "EMS-related school subjects recommended",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Mathematics and Languages (Code 4515)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Mathematics and Natural Sciences (Code 4516)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematics and Natural Sciences required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Education",
  qualification: "BEd Foundation Phase Teaching (Code 4517)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another official language may be required",
  apply_url: "https://www.uwc.ac.za"
},
//Faculty of Economic and Management Sciences
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce (BCom) (Code 1008)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Administration (Code 1011)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy Level 5 accepted in place of Mathematics",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Administration (Part Time) (Code 1018)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy Level 5 accepted in place of Mathematics",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Accounting (Code 1021)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Accounting recommended/required as specified by the faculty",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Information Systems (Code 1033)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce (Part-Time) (Code 1101)",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Financial Accounting (Code 1175)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Economics in Development Economics (Code 1181)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Law (Code 1221)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another language Level 3",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Higher Certificate in Economic Development (Code 1403)",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Accepted",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "NSC Higher Certificate admission requirements",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce – General (4 Year) (Code 1751)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Accounting (4 Year) (Code 1753)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce – ECP (Code 1761)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Economic and Management Sciences",
  qualification: "Bachelor of Commerce in Accounting – ECP (Code 1762)",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended Curriculum Programme",
  apply_url: "https://www.uwc.ac.za"
},
//Faculty of Dentistry
{
  faculty: "Faculty of Dentistry",
  qualification: "Bachelor of Dental Surgery (BDS) (Code 5101)",
  qualification_type: "Degree",
  duration: "5 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: null,
  physical_sciences: "Level 5",
  life_sciences: "Level 5",
  nbt: null,
  additional_requirements: "Competitive selection process applies",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Dentistry",
  qualification: "Bachelor of Oral Health (BOral Health) (Code 5211)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences recommended; selection process applies",
  apply_url: "https://www.uwc.ac.za"
},
//Faculty of Community and Health Sciences
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Science in Sport and Exercise Science",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 33,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 4 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Arts in Sport, Recreation and Exercise Science",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 4",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Selection applies",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Science in Occupational Therapy",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: 33,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 3",
  mathematical_literacy: "Level 5",
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 4 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Science in Physiotherapy",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: 39,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 4 AND Physical Sciences Level 4 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Science in Dietetics",
  qualification_type: "Degree",
  duration: "4 years",
  minimum_aps: 33,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 4 required",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Community and Health Sciences",
  qualification: "Bachelor of Nursing",
  qualification_type: "Degree",
  duration: "4–5 years",
  minimum_aps: 30,
  fps: "UWC Points",
  english_hl: "Level 4 + another language Level 3",
  english_fal: null,
  mathematics: "Level 4",
  mathematical_literacy: "Level 6",
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 4 required",
  apply_url: "https://www.uwc.ac.za"
},
//Faculty of Arts and Humanities
{
  faculty: "Faculty of Arts and Humanities",
  qualification: "Bachelor of Arts (BA)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific APS (50–59%)",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "NSC degree endorsement; subject requirements depend on chosen majors",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Arts and Humanities",
  qualification: "Bachelor of Arts (BA) – 4 Year Extended",
  qualification_type: "Degree (Extended)",
  duration: "4 years",
  minimum_aps: null,
  fps: "Programme specific APS (50–59%)",
  english_hl: "Level 4 (50–59%)",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Extended curriculum for students requiring additional academic support",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Arts and Humanities",
  qualification: "Bachelor of Library and Information Studies (BLIS)",
  qualification_type: "Degree",
  duration: "3 years",
  minimum_aps: null,
  fps: "Programme specific APS (50–59%)",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "NSC degree endorsement; selection may apply",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Arts and Humanities",
  qualification: "Bachelor of Theology (BTh)",
  qualification_type: "Degree",
  duration: "3+ years",
  minimum_aps: null,
  fps: "Programme specific APS (50–59%)",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "NSC degree endorsement; applicants must meet faculty admission requirements",
  apply_url: "https://www.uwc.ac.za"
},
{
  faculty: "Faculty of Arts and Humanities",
  qualification: "Bachelor of Theology (BTh) Part Time",
  qualification_type: "Degree",
  duration: "3+ years (Part Time)",
  minimum_aps: null,
  fps: "Programme specific APS (50–59%)",
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: null,
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Part-time study option; admission requirements apply",
  apply_url: "https://www.uwc.ac.za"
}
]
export async function seedUWC(db: SQLite.SQLiteDatabase) {
  const uni = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["University of the Western Cape"]
  );

  if (!uni) {
    console.error("❌ UWC: university row not found, skipping course seed");
    return;
  }

  for (const course of UWC_COURSES) {
    await db.runAsync(
      `INSERT INTO courses (
        institution_id, institution_type, faculty, qualification, qualification_type,
        duration, province, minimum_aps, fps, english_hl, english_fal, mathematics,
        mathematical_literacy, physical_sciences, life_sciences, nbt,
        additional_requirements, apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        uni.id,
        "university",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "Eastern Cape",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ]
    );
  }
  console.log("✅ Seeded UWC courses");
}