import * as SQLite from "expo-sqlite";

type CourseSeed = {
  faculty: string;
  qualification: string;
  qualification_type: string;
  duration: string;
  minimum_aps: number | null;
  fps: string | null;
  english_hl: string | null;
  english_fal: string | null;
  mathematics: string | null;
  mathematical_literacy: string | null;
  physical_sciences: string | null;
  life_sciences: string | null;
  nbt: string | null;
  additional_requirements: string;
  apply_url: string;
};

const UFS_COURSES: CourseSeed[] = [
  // ======================================================
  // FACULTY OF EDUCATION
  // ======================================================

  {
    faculty: "Faculty of Education",
    qualification: "BEd Foundation Phase – Afrikaans HL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Foundation Phase – Sesotho HL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Sesotho HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Foundation Phase – isiZulu HL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "isiZulu HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Foundation Phase – English HL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "English HL 50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans Level 4 required.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Mathematics, Natural Sciences & Technology (Afrikaans)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Life Skills & Social Sciences (Afrikaans)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Mathematics, Natural Sciences & Technology (English)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "English HL 50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans/Sesotho FAL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Life Skills & Social Sciences (English)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "English HL 50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans/Sesotho FAL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Mathematics, Natural Sciences & Technology (Sesotho)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Sesotho HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Life Skills & Social Sciences (Sesotho)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Sesotho HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Mathematics, Natural Sciences & Technology (isiZulu)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "isiZulu HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Intermediate Phase – Life Skills & Social Sciences (isiZulu)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Not required",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "isiZulu HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Senior & FET – Accounting & Business Studies",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Accounting & Business Studies 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Senior & FET – EMS & Accounting",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements:
      "Accounting plus Economics/Business Studies.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Technology & Engineering Graphics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Engineering Graphics & Design 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Life Sciences & Mathematics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: "60%",
    nbt: "No",
    additional_requirements: "Life Sciences 60%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Technology & Life Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: "60%",
    nbt: "No",
    additional_requirements: "Life Sciences 60%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Sesotho HL & English FAL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Sesotho HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – isiZulu HL & English FAL",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "isiZulu HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Mathematics & Physical Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Physical Sciences 60%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Senior & FET – Sesotho HL & History",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Sesotho HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Senior & FET – isiZulu HL & History",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "isiZulu HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification: "BEd Senior & FET – English & History",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "None.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Afrikaans HL & English",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "No",
    additional_requirements: "Afrikaans HL 50%.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Education",
    qualification:
      "BEd Senior & FET – Geography & Life Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "40%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: "60%",
    nbt: "No",
    additional_requirements: "Geography & Life Sciences 60%.",
    apply_url: "https://www.ufs.ac.za",
  },

  // ======================================================
  // FACULTY OF HEALTH SCIENCES
  // ======================================================

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Medical Science (Radiation Science)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "MBChB",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 36,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Optometry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "BSc Physiotherapy",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "BSc Dietetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Occupational Therapy",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Biokinetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Sport Coaching",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Physical Sciences/Life Sciences where applicable. Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Nursing",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "40% or Mathematical Literacy 70%",
    mathematical_literacy: "70%",
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  // ======================================================
  // FACULTY OF LAW
  // ======================================================

  {
    faculty: "Faculty of Law",
    qualification: "Bachelor of Laws (LLB)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "70%",
    english_fal: null,
    mathematics: "50% or Mathematical Literacy 70%",
    mathematical_literacy: "70%",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "No selection.",
    apply_url: "https://www.ufs.ac.za",
  },

  // ======================================================
  // FACULTY OF NATURAL AND AGRICULTURAL SCIENCES
  // ======================================================

  // BSc Biological Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Behavioural Genetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Botany",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Entomology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Genetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Physiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Statistics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biochemistry & Zoology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Biodiversity & Conservation Ecology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Entomology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Genetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Plant Breeding",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Plant Pathology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Botany & Zoology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Entomology & Genetics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Entomology & Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Entomology & Zoology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Genetics & Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Genetics & Physiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Genetics & Zoology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Microbiology & Statistics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Microbiology & Zoology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Plant Health Ecology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Biological Sciences – Plant Health Management",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // BSc Forensic Science

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Forensic Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "70%",
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  // BSc Mathematical Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Mathematical Sciences – Mathematics & Applied Mathematics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Mathematical Sciences – Mathematics & Chemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Mathematical Sciences – Mathematics & Mathematical Statistics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Mathematical Sciences – Mathematics & Physics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Actuarial Science

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Actuarial Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  // Mathematical Statistics & Applied Statistics

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Mathematical Statistics & Applied Statistics – Climate Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Mathematical Statistics & Applied Statistics – Econometrics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Mathematical Statistics & Applied Statistics – Mathematical Statistics & Psychometrics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Mathematical Statistics & Applied Statistics – Statistics & Economics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Mathematical Statistics & Applied Statistics – Statistics & Psychology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Chemical Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Chemical Sciences – Chemistry & Biochemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Chemical Sciences – Chemistry & Botany",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Chemical Sciences – Chemistry & Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Chemical Sciences – Chemistry & Physics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "Not Required",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Physical Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Physical Sciences – Physics & Agrometeorology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Physical Sciences – Physics & Astrophysics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "Not Required",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Engineering & Physical Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Physics & Engineering Subjects",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Agricultural & Biosystems Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Geography & Environmental Sciences

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geography & Environmental Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "Not Required",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geography Specialisation",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Environmental Soil Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Geology

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geology & Chemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Environmental Geology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geochemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Geology & Physics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Agricultural Economics

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Agricultural Economics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Information Technology

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Information Technology – Computer Science & Chemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Information Technology – Computer Science & Mathematical Statistics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Information Technology – Computer Science & Mathematics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Information Technology – Computer Science & Physics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "BSc Information Technology – Data Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification:
      "BSc Information Technology – Computer Science & Business Management",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.ufs.ac.za",
  },

  // Computer Information Systems

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Bachelor of Computer Information Systems",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 33,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },

  // Sustainable Food Systems

  {
    faculty: "Faculty of Natural and Agricultural Sciences",
    qualification: "Bachelor of Sustainable Food Systems",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "30% or Mathematical Literacy 60%",
    mathematical_literacy: "60%",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.ufs.ac.za",
  },
];

// ======================================================
// SEED UNIVERSITY OF THE FREE STATE
// ======================================================

export const seedUFS = async (db: SQLite.SQLiteDatabase) => {
  const ufs = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["University of the Free State"]
  );

  if (!ufs) {
    throw new Error("University of the Free State not found.");
  }

  const institutionId = ufs.id;

  for (const course of UFS_COURSES) {
    const existing = await db.getFirstAsync<{ id: number }>(
      `SELECT id FROM courses
       WHERE institution_id = ?
       AND qualification = ?`,
      [institutionId, course.qualification]
    );

    if (existing) {
      continue;
    }

    await db.runAsync(
      `INSERT INTO courses (
        institution_id,
        institution_type,
        faculty,
        qualification,
        qualification_type,
        duration,
        province,
        minimum_aps,
        fps,
        english_hl,
        english_fal,
        mathematics,
        mathematical_literacy,
        physical_sciences,
        life_sciences,
        nbt,
        additional_requirements,
        apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        institutionId,
        "university",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "Free State",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ]
    );
  }

  console.log(
    `UFS seeded: ${UFS_COURSES.length} courses across faculties.`
  );
};