import * as SQLite from "expo-sqlite";

// ======================================================
// UNIVERSITY OF VENDA (UNIVEN)
// ======================================================

export const UNIVEN_COURSES = [

  // ======================================================
  // FACULTY OF MANAGEMENT, COMMERCE AND LAW
  // ======================================================

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Laws (LLB)",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 38,
    fps: null,
    english_hl: "60%",
    english_fal: "60%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass; competitive selection may apply.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Arts in Criminal Justice",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Administration",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Accounting",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Mathematics preferred",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics preferred.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Business Information Systems",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Mathematics preferred",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics preferred.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Business Management",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Cost & Management Accounting",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Mathematics preferred",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics preferred.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Economics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Mathematics preferred",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics preferred.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Human Resource Management",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Tourism Management",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Bachelor of Commerce in Public Administration",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  // ======================================================
  // EXTENDED DEGREE PROGRAMMES
  // ======================================================

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended Bachelor of Administration",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Accounting",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Business Information Systems",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Business Management",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Cost & Management Accounting",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Economics",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Human Resource Management",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Management, Commerce and Law",
    qualification: "Extended BCom Tourism Management",
    qualification_type: "Extended Bachelor's Degree",
    duration: "Extended",
    minimum_aps: 28,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "APS 28–31 may be considered for eligible extended programmes.",
    apply_url: "https://www.univen.ac.za",
  },

  // ======================================================
  // FACULTY OF SCIENCE, ENGINEERING AND AGRICULTURE
  // ======================================================

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Agriculture",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 26,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics and Physical Sciences required.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Animal Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 26,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics and Physical Sciences required.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Crop Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 26,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Required",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics and Physical Sciences required.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Environmental Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 32,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics 50% and Physical Sciences 50%.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Hydrology & Water Resources",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 35,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics 50% and Physical Sciences 50%.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Mining & Environmental Geology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 35,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Mathematics 50% and Physical Sciences 50%.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Computer Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "Recommended",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Physical Sciences recommended.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Information Systems",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "50%",
    mathematical_literacy: null,
    physical_sciences: "Recommended",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Physical Sciences recommended.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Mathematics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "Recommended",
    life_sciences: null,
    nbt: null,
    additional_requirements: "Physical Sciences recommended.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Physics",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Chemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Biochemistry",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Microbiology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Science, Engineering and Agriculture",
    qualification: "BSc Biotechnology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "",
    apply_url: "https://www.univen.ac.za",
  },

  // ======================================================
  // FACULTY OF HUMANITIES, SOCIAL SCIENCES AND EDUCATION
  // ======================================================

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Arts (General)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "BA Media Studies",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "BA Development Studies",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "BA English & Literature",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "BA International Relations",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "BA Language Practice",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Indigenous Knowledge Systems",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 30,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Bachelor's pass.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Social Work",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 35,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Education (Foundation Phase)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 36,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Teaching subject requirements; selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Education (Intermediate Phase)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 36,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Teaching subject requirements; selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Humanities, Social Sciences and Education",
    qualification: "Bachelor of Education (Senior & FET Phase)",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 36,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Teaching subject requirements; selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  // ======================================================
  // FACULTY OF HEALTH SCIENCES
  // ======================================================

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Nursing",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 38,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "Competitive selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Nutrition",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "50%",
    nbt: null,
    additional_requirements: "Competitive selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Public Health",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "50%",
    nbt: null,
    additional_requirements: "Competitive selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Sports Science",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 34,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "50%",
    nbt: null,
    additional_requirements: "Competitive selection programme.",
    apply_url: "https://www.univen.ac.za",
  },

  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Psychology",
    qualification_type: "Bachelor's Degree",
    duration: "Not Specified",
    minimum_aps: 36,
    fps: null,
    english_hl: "50%",
    english_fal: "50%",
    mathematics: "Required",
    mathematical_literacy: null,
    physical_sciences: "Recommended",
    life_sciences: "Recommended",
    nbt: null,
    additional_requirements: "Competitive selection programme.",
    apply_url: "https://www.univen.ac.za",
  },
];


// ======================================================
// SEED UNIVEN
// ======================================================

export const seedUNIVEN = async (db: SQLite.SQLiteDatabase) => {
  const univen = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["University of Venda"]
  );

  if (!univen) {
    throw new Error("University of Venda not found.");
  }

  const institutionId = univen.id;

  for (const course of UNIVEN_COURSES) {
    const existing = await db.getFirstAsync<{ id: number }>(
      `SELECT id FROM courses
       WHERE institution_id = ?
       AND qualification = ?`,
      [institutionId, course.qualification]
    );

    if (existing) {
      continue;
    }

    await db.runAsync(
      `INSERT INTO courses (
        institution_id,
        institution_type,
        faculty,
        qualification,
        qualification_type,
        duration,
        province,
        minimum_aps,
        fps,
        english_hl,
        english_fal,
        mathematics,
        mathematical_literacy,
        physical_sciences,
        life_sciences,
        nbt,
        additional_requirements,
        apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        institutionId,
        "university",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "Limpopo",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ],
    );
  }

  console.log(
    `UNIVEN seeded: ${UNIVEN_COURSES.length} courses across faculties.`
  );
};