import * as SQLite from "expo-sqlite";

type CourseSeed = {
  faculty: string;
  qualification: string;
  qualification_type: string;
  duration: string;
  minimum_aps: number | null;
  fps: string | null;
  english_hl: string | null;
  english_fal: string | null;
  mathematics: string | null;
  mathematical_literacy: string | null;
  physical_sciences: string | null;
  life_sciences: string | null;
  nbt: string | null;
  additional_requirements: string;
  apply_url: string;
};

const WITS_COURSES: CourseSeed[] = [
  // ==================== COMMERCE, LAW AND MANAGEMENT ====================
  {
    faculty: "School of Business Sciences",
    qualification: "Bachelor of Commerce (BCom) General",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 38,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 35-37, English Level 5 and Mathematics Level 5 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "The Wits Margo Steele School of Accountancy",
    qualification: "Bachelor of Accounting Science (BAccSci)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 44,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 39-43, English Level 6 and Mathematics Level 6 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "The Wits Margo Steele School of Accountancy",
    qualification: "Bachelor of Commerce (BCom) Accounting",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 38,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 35-37, English Level 5 and Mathematics Level 5 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Economics and Finance",
    qualification: "Bachelor of Economic Science (BEconSci)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 7",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 39-41, English Level 5 and Mathematics Level 7 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Economics and Finance",
    qualification: "Bachelor of Commerce (BCom) Financial Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 7",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 39-41, English Level 5 and Mathematics Level 7 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Law",
    qualification: "Bachelor of Commerce (BCom) Law",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 35-42, English Level 6 and Mathematics Level 6 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Law",
    qualification: "Bachelor of Laws (LLB) Four-Year",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 46,
    fps: null,
    english_hl: "Level 6",
    english_fal: "Level 6",
    mathematics: "Level 5",
    mathematical_literacy: "Level 6",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants with APS 40-45, English Level 6 and Mathematics Level 5 OR Maths Literacy Level 6 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },

  // ==================== ENGINEERING AND THE BUILT ENVIRONMENT ====================
  {
    faculty: "School of Chemical and Metallurgical Engineering",
    qualification: "BSc(Eng) Chemical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Chemical and Metallurgical Engineering",
    qualification: "BSc(Eng) Metallurgy and Materials Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Civil and Environmental Engineering",
    qualification: "BSc(Eng) Civil Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Electrical and Information Engineering",
    qualification: "BSc(Eng) Electrical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Electrical and Information Engineering",
    qualification: "BEngSc Biomedical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Electrical and Information Engineering",
    qualification: "BEngSc Digital Arts",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Mechanical, Industrial and Aeronautical Engineering",
    qualification: "BSc(Eng) Aeronautical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Mechanical, Industrial and Aeronautical Engineering",
    qualification: "BSc(Eng) Industrial Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Mechanical, Industrial and Aeronautical Engineering",
    qualification: "BSc(Eng) Mechanical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Mining Engineering",
    qualification: "BSc(Eng) Mining Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Generally, applicants who achieve Level 6 in English, Mathematics and Physical Sciences stand a greater chance of being accepted",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Architecture and Planning",
    qualification: "Bachelor of Architectural Studies (BAS)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 4",
    english_fal: "Level 4",
    mathematics: "Level 4",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Acceptance depends on departmental selection. Applicants must complete a written and graphic exercise and may be required to attend an interview",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Architecture and Planning",
    qualification: "BSc Urban and Regional Planning (BSc(URP))",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 30-35 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Construction Economics and Management",
    qualification: "BSc Construction Studies (BSc(CS))",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 30-35 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Construction Economics and Management",
    qualification: "BSc Property Studies (BSc(PS))",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 30-35 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },

  // ==================== HEALTH SCIENCES ====================
  {
    faculty: "Faculty of Health Sciences",
    qualification: "BHSc Biokinetics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "BHSc Biomedical Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "BHSc Health Systems Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Clinical Medical Practice (BCMP)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 4",
    english_fal: "Level 4",
    mathematics: "Level 4",
    mathematical_literacy: "Level 7",
    physical_sciences: "Level 4",
    life_sciences: "Level 4",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "MBBCh (Medicine)",
    qualification_type: "Bachelor's Degree",
    duration: "6 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Dental Science (BDS)",
    qualification_type: "Bachelor's Degree",
    duration: "5 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "16 hours job shadowing required (1 July 2025 - 31 July 2026)",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Oral Health Sciences (BOHS)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 4",
    english_fal: "Level 4",
    mathematics: "Level 4",
    mathematical_literacy: "Level 7",
    physical_sciences: "Level 4",
    life_sciences: "Level 4",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "16 hours job shadowing required (1 July 2025 - 31 July 2026)",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Nursing (BNurs)",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 4",
    english_fal: "Level 4",
    mathematics: "Level 4",
    mathematical_literacy: null,
    physical_sciences: "Level 4",
    life_sciences: "Level 4",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "Bachelor of Pharmacy (BPharm)",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "Composite Index (CI) used: 60% academic results + 40% NBT scores",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "BSc Occupational Therapy",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 4",
    english_fal: "Level 4",
    mathematics: "Level 4",
    mathematical_literacy: null,
    physical_sciences: "Level 4",
    life_sciences: "Level 4",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "16 hours job shadowing required (1 July 2025 - 31 July 2026)",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Health Sciences",
    qualification: "BSc Physiotherapy",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: "Level 5",
    nbt: "Required by 17 August 2026",
    additional_requirements:
      "16 hours job shadowing required (1 July 2025 - 31 July 2026)",
    apply_url: "https://www.wits.ac.za",
  },

  // ==================== HUMANITIES ====================
  {
    faculty: "Faculty of Humanities",
    qualification: "Bachelor of Arts (BA) General",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 30-35 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Faculty of Humanities",
    qualification: "Bachelor of Arts (Law)",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 3",
    mathematical_literacy: "Level 4",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 40-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Arts",
    qualification: "BA Digital Arts",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Applicants must attend a digital arts workshop and/or complete a questionnaire",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Arts",
    qualification: "BA Film and Television",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Portfolio submission and interview required",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Arts",
    qualification: "BA Fine Arts",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Portfolio submission and questionnaire required",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Arts",
    qualification: "Bachelor of Music (BMus)",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Audition and interview required",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Arts",
    qualification: "BA Theatre and Performance",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Audition/interview required (bookings close October 2026)",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Education",
    qualification: "BEd Foundation Phase Teaching",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 37,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 4",
    mathematical_literacy: "Level 5",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 34-36 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Education",
    qualification: "BEd Intermediate Phase Teaching",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 37,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 4",
    mathematical_literacy: "Level 5",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 34-36 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "Wits School of Education",
    qualification: "BEd Senior Phase and FET Teaching",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 37,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "Applicants with APS 34-36 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Human and Community Development",
    qualification: "Bachelor of Audiology",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 4",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 17 August 2026",
    additional_requirements: "Only 30 places available",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Human and Community Development",
    qualification: "Bachelor of Speech-Language Pathology",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 34,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 4",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 17 August 2026",
    additional_requirements: "Only 30 places available",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Human and Community Development",
    qualification: "Bachelor of Social Work",
    qualification_type: "Bachelor's Degree",
    duration: "4 Years",
    minimum_aps: 36,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "Only 60 places available. Selected on academic merit within various school quintiles",
    apply_url: "https://www.wits.ac.za",
  },

  // ==================== SCIENCE ====================
  // Biological Sciences
  {
    faculty: "School of Animal, Plant and Environmental Sciences",
    qualification: "BSc Applied Ecology",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Animal, Plant and Environmental Sciences",
    qualification: "BSc Biodiversity in a Changing World",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Molecular and Cell Biology",
    qualification: "BSc Applied Bioinformatics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Molecular and Cell Biology",
    qualification: "BSc Biochemistry and Cell Biology",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Molecular and Cell Biology",
    qualification: "BSc Genetics and Developmental Biology",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Molecular and Cell Biology",
    qualification: "BSc Microbiology and Biotechnology",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  // Earth Sciences
  {
    faculty: "School of Geography, Archaeology and Environmental Studies",
    qualification: "BSc Geographical and Archaeological Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Geography, Archaeology and Environmental Studies",
    qualification: "BSc Environmental Studies",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Geography, Archaeology and Environmental Studies",
    qualification: "BSc Geospatial Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 5",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Geosciences",
    qualification: "BSc Geological Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  // Mathematical Sciences
  {
    faculty: "School of Statistics and Actuarial Science",
    qualification: "BSc Actuarial Science",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 44,
    fps: null,
    english_hl: "Level 7",
    english_fal: "Level 7",
    mathematics: "Level 7",
    mathematical_literacy: null,
    physical_sciences: "Level 7",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements:
      "Applicants with 44+ points, English Level 6, Mathematics Level 7 and Physical Sciences Level 7 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Computer Science and Applied Mathematics",
    qualification: "BSc Computational and Applied Mathematics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 44,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-43 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Computer Science and Applied Mathematics",
    qualification: "BSc Computer Science",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 44,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 41-43 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Mathematics",
    qualification: "BSc Mathematical Sciences",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 44,
    fps: null,
    english_hl: "Level 7",
    english_fal: "Level 7",
    mathematics: "Level 7",
    mathematical_literacy: null,
    physical_sciences: "Level 7",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements:
      "Applicants with 44+ points, English Level 6, Mathematics Level 7 and Physical Sciences Level 7 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  // Physical Sciences
  {
    faculty: "School of Chemistry",
    qualification: "BSc Chemistry",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Chemistry",
    qualification: "BSc Chemistry with Chemical Engineering",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: "Level 6",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Physics",
    qualification: "BSc Astronomy and Astrophysics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 43,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: "Level 6",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-42 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
  {
    faculty: "School of Physics",
    qualification: "BSc Physics",
    qualification_type: "Bachelor's Degree",
    duration: "3 Years",
    minimum_aps: 42,
    fps: null,
    english_hl: "Level 5",
    english_fal: "Level 5",
    mathematics: "Level 6",
    mathematical_literacy: null,
    physical_sciences: "Level 5",
    life_sciences: null,
    nbt: "Required by 31 October 2026",
    additional_requirements: "Applicants with 40-41 may be wait-listed",
    apply_url: "https://www.wits.ac.za",
  },
];

export const seedWits = async (refDb: SQLite.SQLiteDatabase) => {
  try {
    const wits = await refDb.getFirstAsync<{ id: number }>(
      "SELECT id FROM universities WHERE name = ?",
      ["University of the Witwatersrand"],
    );

    if (!wits) {
      console.log(
        "⚠️ Wits not found in universities table. Run seedUniversities first.",
      );
      return;
    }

    const institutionId = wits.id;

    for (const course of WITS_COURSES) {
      const existing = await refDb.getFirstAsync<{ id: number }>(
        `SELECT id FROM courses
         WHERE institution_id = ?
         AND qualification = ?`,
        [institutionId, course.qualification],
      );

      if (existing) {
        continue;
      }

      await refDb.runAsync(
        `INSERT INTO courses (
          institution_id,
          institution_type,
          faculty,
          qualification,
          qualification_type,
          duration,
          province,
          minimum_aps,
          fps,
          english_hl,
          english_fal,
          mathematics,
          mathematical_literacy,
          physical_sciences,
          life_sciences,
          nbt,
          additional_requirements,
          apply_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          institutionId,
          "university",
          course.faculty,
          course.qualification,
          course.qualification_type,
          course.duration,
          "Gauteng",
          course.minimum_aps,
          course.fps,
          course.english_hl,
          course.english_fal,
          course.mathematics,
          course.mathematical_literacy,
          course.physical_sciences,
          course.life_sciences,
          course.nbt,
          course.additional_requirements,
          course.apply_url,
        ],
      );
    }

    console.log(
      `✅ Wits seeded: ${WITS_COURSES.length} courses across faculties.`,
    );
  } catch (error) {
    console.error("❌ Seed Wits error:", error);
  }
};
