import * as SQLite from "expo-sqlite";

type CourseSeed = {
  faculty: string;
  qualification: string;
  qualification_type: string;
  duration: string;
  minimum_aps: number | null;
  fps: string | null;
  english_hl: string | null;
  english_fal: string | null;
  mathematics: string | null;
  mathematical_literacy: string | null;
  physical_sciences: string | null;
  life_sciences: string | null;
  nbt: string | null;
  additional_requirements: string;
  apply_url: string;
};

export const TUT_COURSES: CourseSeed[] = [
    //Faculty of Science
{
  faculty: "Science",
  qualification: "Diploma in Animal Sciences",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 19,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Crop Production",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 19,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy Level 4 accepted.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Equine Science",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 19,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Horticulture",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 25,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: "Level 3",
  nbt: null,
  additional_requirements: "Life Sciences, Physical Sciences or Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Landscape Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 25,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: "Level 3",
  nbt: null,
  additional_requirements: "Life Sciences, Physical Sciences or Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Nature Conservation",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Agricultural Sciences, Geography, Life Sciences, Physical Sciences or Technical Sciences.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Wildlife Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Agricultural Sciences, Geography, Life Sciences, Physical Sciences or Technical Sciences.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Higher Certificate in Forestry Management",
  qualification_type: "Higher Certificate",
  duration: "2 years",
  minimum_aps: 18,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy accepted at Level 6.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Environmental Health",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4, Life Sciences Level 4, plus two other subjects at Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Nursing",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 27,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Only offered at Mbombela Campus.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Pharmacy",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Radiography in Diagnostics",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Health Sciences (Biokinetics)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Health Sciences (Clinical Technology)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Health Sciences (Medical Laboratory Science)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Health Sciences (Medical Orthotics and Prosthetics)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Health Sciences (Veterinary Technology)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Kinesiology and Coaching Science",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Somatic Therapy",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Higher Certificate in Dental Assisting",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences Level 5. Any other additional subjects Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Bachelor of Science in Industrial Chemistry",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 5",
  life_sciences: null,
  nbt: null,
  additional_requirements: "No Physical Sciences Level 5.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Analytical Chemistry",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Biotechnology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 3",
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Environmental Sciences",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences or Agricultural Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Fire Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: null,
  fps: null,
  english_hl: "N/A",
  english_fal: null,
  mathematics: "N/A",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Only for Fire and Rescue Services personnel. Requires an appropriate NSC (or equivalent), 3 years' relevant work experience, HAZMAT Awareness, Fire Fighter I, HAZMAT Operational, Fire Fighter II certificates, and proof of employment.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Food Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4 and Life Sciences or Agricultural Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Geology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 21,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Industrial Physics",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 21,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Diploma in Water Science and Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 21,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Higher Certificate in Resource and Waste Management",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 18,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy accepted at Level 6.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Science",
  qualification: "Higher Certificate in Water Treatment",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 18,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy accepted at Level 6. Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
//Faculty of Management Sciences
{
  faculty: "Management Sciences",
  qualification: "Diploma in Administrative Information Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Adventure Tourism Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Casino Resort Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Contact Centre Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Credit Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Accounting Level 3 required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Ecotourism Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Entrepreneurship",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Event Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Food Operations Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Hospitality Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Human Resource Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Marketing",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Operations Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Retail Business Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Online presentation.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Sport Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Supply Chain Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Tourism Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Diploma in Work Study",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Higher Certificate in Administrative Information Management",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Online presentation.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Management Sciences",
  qualification: "Higher Certificate in Contact Centre Management",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Online presentation.",
  apply_url: "https://www.wsu.ac.za"
},
//Faculty of Information and Communication Technology
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Science",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Science (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Systems Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 4 required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Systems Engineering (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Informatics",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Informatics (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Information Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required. Mathematical Literacy applicants require Level 7 and APS 28.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Information Technology (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required. Mathematical Literacy applicants require Level 6 and APS 25.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Multimedia Computing",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Multimedia Computing (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Science",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Science (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Systems Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 4 required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Computer Systems Engineering (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Informatics",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Informatics (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Information Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required. Mathematical Literacy applicants require Level 7 and APS 28.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Information Technology (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3 required. Mathematical Literacy applicants require Level 6 and APS 25.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Multimedia Computing",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 7 and APS 28. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Information and Communication Technology",
  qualification: "Diploma in Multimedia Computing (Extended)",
  qualification_type: "Diploma (Extended)",
  duration: "4 years",
  minimum_aps: 23,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy applicants require Level 6 and APS 25. Recommended subject: Information Technology.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Foundation Phase Teaching)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 25,
  fps: null,
  english_hl: "Level 5",
  english_fal: "Level 4",
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "First Additional Language Level 4 and Home Language offered in the programme.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Intermediate Phase Teaching)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 25,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another Home Language Level 4 and either Life Sciences & Physical Sciences or History & Geography at Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Agriculture)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Agricultural Sciences or Life Sciences Level 4, and Agricultural Technology or Physical Sciences or Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Consumer Sciences)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Consumer Studies or Hospitality Studies or Tourism Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Economic & Management Sciences)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Accounting or Business Studies or Economics Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Information Technology)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Information Technology Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Mathematics)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences or Physical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Physical Education)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 4",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Life Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Sciences)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: "Level 4",
  nbt: null,
  additional_requirements: "Life Sciences or Physical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Bachelor of Education (Senior Phase & FET Teaching – Technology)",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "One or more of: Civil Technology, Electrical Technology, Mechanical Technology, Engineering Graphics and Design, Physical Sciences or Technical Sciences.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Adult and Community Education and Training (Civil Technology)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Engineering Graphics and Design or Mathematics or Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Civil Technology or Physical Sciences or Technical Sciences Level 3; Additional Language Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Adult and Community Education and Training (Consumer Sciences)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Additional Language Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Adult and Community Education and Training (Electrical and Mechanical)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences or Technical Sciences Level 3; Additional Language Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Correctional and Rehabilitation Studies",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Integrated Communication",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics/Engineering Mathematics N3 Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Mathematical Literacy accepted.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Journalism",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Language Practice",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Another official South African language offered in the programme at Level 5. Preference given to applicants with English Level 5 or higher.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Law",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Legal Support",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Additional Language Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Policing",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Separate admission requirements apply for applicants already employed in law enforcement.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Public Affairs (Administration of State)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Public Affairs (Local Government)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Humanities",
  qualification: "Diploma in Traffic Safety and Municipal Police",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics or Mathematical Literacy Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Separate admission requirements apply for applicants already employed in law enforcement.",
  apply_url: "https://www.wsu.ac.za"
},
//Faculty of Engineering and the Built Environment
{
  faculty: "Engineering and the Built Environment",
  qualification: "Bachelor of Architecture",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 28,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4. Selection process required.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Bachelor of Engineering Technology in Civil Engineering",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Bachelor of Engineering Technology in Electrical Engineering",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Bachelor of Engineering Technology in Industrial Engineering",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Bachelor of Engineering Technology in Mechanical Engineering",
  qualification_type: "Bachelor's Degree",
  duration: "4 years",
  minimum_aps: 26,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 5",
  mathematical_literacy: "No",
  physical_sciences: "Level 4",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 4.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Building",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Civil Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Electrical Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Industrial Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Mechanical Engineering",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Diploma in Surveying",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4",
  mathematical_literacy: "No",
  physical_sciences: "Level 3",
  life_sciences: null,
  nbt: null,
  additional_requirements: "Physical Sciences/Technical Sciences Level 3.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Higher Certificate in Construction Engineering",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Engineering and the Built Environment",
  qualification: "Higher Certificate in Surveying",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "No",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Accounting",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Accounting Level 3 or Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires English Level 4 and one of: Accounting, Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Economics",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Financial Management",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Accounting Level 3 or Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires English Level 4 and one of: Accounting, Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Financial Planning",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Accounting Level 3 or Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires English Level 4 and one of: Accounting, Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Internal Auditing",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Accounting Level 3 or Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires English Level 4 and one of: Accounting, Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Diploma in Public Finance",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 4 or Accounting Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires English Level 4 and one of: Accounting, Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Economics and Finance",
  qualification: "Higher Certificate in Economics and Finance",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Mathematics/Technical Mathematics Level 3",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Requires Mathematics, Technical Mathematics or Mathematical Literacy.",
  apply_url: "https://www.wsu.ac.za"
},
//Faculty of Arts and Design
{
  faculty: "Arts and Design",
  qualification: "Diploma in Commercial Photography",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Fashion Design and Technology",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Fine and Applied Arts",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Integrated Communication Design",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 24,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Interior Design",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "Recommended subjects: Civil Technology, Design Studies, Engineering Graphics and Design, Visual Arts.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Jewellery Design and Manufacture",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Motion Picture Production",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 22,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Performing Arts (Dance)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Performing Arts (Jazz Music)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Performing Arts (Opera)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Performing Arts (Technical Theatre and Design)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Diploma in Performing Arts (Theatre Arts and Performance)",
  qualification_type: "Diploma",
  duration: "3 years",
  minimum_aps: 20,
  fps: null,
  english_hl: "Level 4",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
{
  faculty: "Arts and Design",
  qualification: "Higher Certificate in Music",
  qualification_type: "Higher Certificate",
  duration: "1 year",
  minimum_aps: 18,
  fps: null,
  english_hl: "Level 3",
  english_fal: null,
  mathematics: "Not Required",
  mathematical_literacy: "Yes",
  physical_sciences: null,
  life_sciences: null,
  nbt: null,
  additional_requirements: "None specified.",
  apply_url: "https://www.wsu.ac.za"
},
]
export async function seedTUT(db: SQLite.SQLiteDatabase) {
  const uni = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["Tshwane University of Technology"]
  );

  if (!uni) {
    console.error("❌ TUT: university row not found, skipping course seed");
    return;
  }

  for (const course of TUT_COURSES) {
    await db.runAsync(
      `INSERT INTO courses (
        institution_id, institution_type, faculty, qualification, qualification_type,
        duration, province, minimum_aps, fps, english_hl, english_fal, mathematics,
        mathematical_literacy, physical_sciences, life_sciences, nbt,
        additional_requirements, apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        uni.id,
        "university",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "Eastern Cape",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ]
    );
  }
  console.log("✅ Seeded TUT courses");
}