import * as SQLite from "expo-sqlite";

// ======================================================
// STELLENBOSCH UNIVERSITY (SU)
// ======================================================

export const STELLENBOSCH_COURSES = [

  // ======================================================
  // FACULTY OF AGRISCIENCES
  // ======================================================

  {
    faculty: "AgriSciences",
    qualification: "BSc in Forestry (Forestry & Natural Resources Sciences)",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "AgriSciences",
    qualification: "BSc in Forestry (Wood & Wood Products Sciences)",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "AgriSciences",
    qualification: "BAgric in Agricultural Production & Management (Elsenburg)",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "AgriSciences",
    qualification: "BScAgric",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "AgriSciences",
    qualification: "BSc Food Science",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF ARTS AND SOCIAL SCIENCES
  // ======================================================

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Faculty selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA International Studies",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA Humanities",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA Language and Culture",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA Development and Environment",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA Sport Science",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%; Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Arts and Social Sciences",
    qualification: "BA in Music",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "Home Language 50%",
    english_fal: "FAL 40%",
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements:
      "NSC Aggregate 60%; Audition and theory test required",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF ECONOMIC AND MANAGEMENT SCIENCES
  // ======================================================

  {
    faculty: "Economic and Management Sciences",
    qualification: "BCom",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 65%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Economic and Management Sciences",
    qualification: "BCom Management Sciences",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 65%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Economic and Management Sciences",
    qualification: "BCom Financial Accounting",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Economic and Management Sciences",
    qualification: "BCom Investment Management",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Economic and Management Sciences",
    qualification: "BCom Mathematical Sciences",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "80%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Economic and Management Sciences",
    qualification: "BAccounting",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF EDUCATION
  // ======================================================

  {
    faculty: "Education",
    qualification: "BEd Foundation Phase",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Education",
    qualification: "BEd Intermediate Phase",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Education",
    qualification: "BEd Senior Phase & FET",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: "Programme specific",
    mathematical_literacy: "Programme specific",
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF ENGINEERING
  // ======================================================

  {
    faculty: "Engineering",
    qualification: "BEng Civil",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Engineering",
    qualification: "BEng Electrical & Electronic",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Engineering",
    qualification: "BEng Industrial",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Engineering",
    qualification: "BEng Mechanical",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Engineering",
    qualification: "BEng Mechatronic",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Engineering",
    qualification: "BEng Chemical",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 70%",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF LAW
  // ======================================================

  {
    faculty: "Law",
    qualification: "BA Law",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Law",
    qualification: "BCom Law",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 65%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Law",
    qualification: "LLB",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "60%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 65%",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF MEDICINE AND HEALTH SCIENCES
  // ======================================================

  {
    faculty: "Medicine and Health Sciences",
    qualification: "MBChB",
    qualification_type: "Undergraduate Degree",
    duration: "6 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "70%",
    life_sciences: "Recommended",
    nbt: null,
    additional_requirements:
      "Competitive Selection; NSC Aggregate: Competitive Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Medicine and Health Sciences",
    qualification: "Occupational Therapy",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements:
      "Competitive Selection; NSC Aggregate: Competitive Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Medicine and Health Sciences",
    qualification: "Physiotherapy",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements:
      "Competitive Selection; NSC Aggregate: Competitive Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Medicine and Health Sciences",
    qualification: "Dietetics",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements:
      "Competitive Selection; NSC Aggregate: Competitive Selection",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Medicine and Health Sciences",
    qualification: "Speech-Language & Hearing Therapy",
    qualification_type: "Undergraduate Degree",
    duration: "4 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements:
      "Competitive Selection; NSC Aggregate: Competitive Selection",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF SCIENCE
  // ======================================================

  {
    faculty: "Science",
    qualification: "BSc Biological Sciences",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "50%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Physical Sciences",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Computer Science",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Applied Mathematics",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Chemistry",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Physics",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "70%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Earth Sciences",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  {
    faculty: "Science",
    qualification: "BSc Molecular Biology & Biotechnology",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: null,
    english_fal: null,
    mathematics: "60%",
    mathematical_literacy: null,
    physical_sciences: "60%",
    life_sciences: "60%",
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },

  // ======================================================
  // FACULTY OF THEOLOGY
  // ======================================================

  {
    faculty: "Theology",
    qualification: "Bachelor of Theology",
    qualification_type: "Undergraduate Degree",
    duration: "3 Years",
    minimum_aps: null,
    fps: null,
    english_hl: "50%",
    english_fal: null,
    mathematics: null,
    mathematical_literacy: null,
    physical_sciences: null,
    life_sciences: null,
    nbt: null,
    additional_requirements: "NSC Aggregate 60%",
    apply_url: "https://www.sun.ac.za",
  },
];

// ======================================================
// SEED STELLENBOSCH UNIVERSITY
// ======================================================

export const seedStellenbosch = async (
  db: SQLite.SQLiteDatabase
) => {
  const stellenbosch = await db.getFirstAsync<{ id: number }>(
    "SELECT id FROM universities WHERE name = ?",
    ["Stellenbosch University"]
  );

  if (!stellenbosch) {
    throw new Error("Stellenbosch University not found.");
  }

  const institutionId = stellenbosch.id;

  for (const course of STELLENBOSCH_COURSES) {
    const existing = await db.getFirstAsync<{ id: number }>(
      `SELECT id FROM courses
       WHERE institution_id = ?
       AND qualification = ?`,
      [institutionId, course.qualification]
    );

    if (existing) {
      continue;
    }

    await db.runAsync(
      `INSERT INTO courses (
        institution_id,
        institution_type,
        faculty,
        qualification,
        qualification_type,
        duration,
        province,
        minimum_aps,
        fps,
        english_hl,
        english_fal,
        mathematics,
        mathematical_literacy,
        physical_sciences,
        life_sciences,
        nbt,
        additional_requirements,
        apply_url
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        institutionId,
        "university",
        course.faculty,
        course.qualification,
        course.qualification_type,
        course.duration,
        "Western Cape",
        course.minimum_aps,
        course.fps,
        course.english_hl,
        course.english_fal,
        course.mathematics,
        course.mathematical_literacy,
        course.physical_sciences,
        course.life_sciences,
        course.nbt,
        course.additional_requirements,
        course.apply_url,
      ]
    );
  }

  console.log(
    `Stellenbosch University seeded: ${STELLENBOSCH_COURSES.length} courses across faculties.`
  );
};